Add type cast to prevent deprecated passing of null value to is_dir
laminas/laminas-component-installer pull request #38
Opened 2021-09-29 13:14 UTC by arueckauer

|    Q          |   A
|----------- | ------
| QA            | yes

### Description

This fixes the deprecated call of `is_dir` with a null value by casting input value for strict comparison with empty string.

See #36.

2021-09-29 22:30 UTC, boesing commented
As written in slack, we should aim to ensure typesafety as required by the php doc rather than allowing mixed just because it can be passed.

The method requires string, if you add native type hint, this will break again.

Please check on why null is being passed to the constructor and ensure that its always string. this will allow us to safely add native type in a future release without having breaking tests which verify that a method can be called with an invalid type.

2021-09-29 22:31 UTC, boesing requested changes
As written in slack, we should aim to ensure typesafety as required by the php doc rather than allowing mixed just because it can be passed.

The method requires string, if you add native type hint, this will break again.

Please check on why null is being passed to the constructor and ensure that its always string. this will allow us to safely add native type in a future release without having breaking tests which verify that a method can be called with an invalid type.

2021-09-30 09:26 UTC, arueckauer commented
After some explanation from @boesing I have a better understanding of the issue and close this in favor of #40 .

2021-09-30 09:26 UTC, closed without merging

2021-09-30 09:35 UTC, boesing commented
Summary form another chat:
- the composer plugin class `ComponentInstaller` has a property `projectRoot` ([link](https://github.com/laminas/laminas-component-installer/blob/223d81cf648ff9380bd13cfe07a31324b0ffc8b8/src/ComponentInstaller.php#L120)) supposed to be string but is actually null due to a check within `__construct` ([link](https://github.com/laminas/laminas-component-installer/blob/223d81cf648ff9380bd13cfe07a31324b0ffc8b8/src/ComponentInstaller.php#L138))
- so `projectRoot` can be `null` when its passed to the [config discovery](https://github.com/laminas/laminas-component-installer/blob/223d81cf648ff9380bd13cfe07a31324b0ffc8b8/src/ComponentInstaller.php#L954)
- this will be passed to the `AbstractDiscovery#__construct`  which then passes it to is_dir ([link](https://github.com/laminas/laminas-component-installer/blob/223d81cf648ff9380bd13cfe07a31324b0ffc8b8/src/ConfigDiscovery/AbstractDiscovery.php#L39))

_(this was btw [detected by psalm](https://github.com/laminas/laminas-component-installer/blob/223d81cf648ff9380bd13cfe07a31324b0ffc8b8/psalm-baseline.xml#L159) already but we’ve passed it to the baseline - no front here!)_